### ISSUE TITLE
Release 1.9 makes screen flicker

### ISSUE THREAD

**Issue by bartv** [arachnidlabs/reload-pro#73]
My screen flickers constantly after flashing version 1.9 (upgrade from 1.6). I tried to downgrade to 1.8 but cyflash will not let me:

[bart@tripel tmp]$ python -m cyflash --serial /dev/ttyUSB0 Reload\ Pro\ v1.8.cyacd 
Initialising bootloader.
Silicon ID 0x04a61193, revision 17.
Array 0: first row 22, last row 255.
Device application_id 0, version 265.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/cyflash/__main__.py", line 2, in <module>
    bootload.main()
  File "/usr/lib/python2.7/site-packages/cyflash/bootload.py", line 217, in main
    "Device app ID %d is different from local app ID %d. Flash anyway? (Y/N)"))
  File "/usr/lib/python2.7/site-packages/cyflash/bootload.py", line 123, in bootload
    self.check_metadata(data, downgrade, newapp)
  File "/usr/lib/python2.7/site-packages/cyflash/bootload.py", line 172, in check_metadata
    if not downgrade(metadata.app_version, local_metadata.app_version):
TypeError: 'NoneType' object is not callable

I tried to reset the device to factory defaults without results.

I recording of the behavior:
https://dl.dropboxusercontent.com/u/3546611/VID_20141116_215231.mp4

**Comment by danielbriggs** [comment]
Having upgraded from V1.3 to V1.9 today, my unit suffers the same flickering.

**Comment by bartv** [comment]
This is fixed with the 1.11 firmware.
